#!/bin/sh

# Ideas and some parts from the original dgl-create-chroot (by joshk@triplehelix.org, modifications by jilles@stack.nl)
# Plus modifications by paxed@alt.org
# This one by codehero@nerdpol.ch


#
# configure dgl with --with-config-file=/path_to_chroot/etc/dgamelaunch.conf, if you want the conf file inside the chroot.
#


# Same as chroot_path in dgl config file
CHROOT="/opt/roguenexus/dgamelaunch"
# the user & group from dgamelaunch config file.
USRGRP="games:games"
# COMPRESS from include/config.h; the compression binary to copy. leave blank to skip.
#COMPRESSBIN="/bin/gzip"
# cdda binary to copy into chroot (leave blank to skip)
echo "Please input the FULL path of the cataclysm binary. Leave empty for /home/$USER/Cataclysm-DDA/cataclysm"
#read CDDABIN
CDDABIN="/Cataclysm-DDA/cataclysm"
#if [ -z $CDDABIN ]
#then
#CDDABIN="/home/$USER/Cataclysm-DDA/cataclysm"
#fi
# dir to copy shared data from
echo "Please input the FULL path of the Cataclysm-DDA folder. Leave empty for /home/$USER/Cataclysm-DDA/"
CDDADIR="/Cataclysm-DDA/"
#read CDDADIR
#if [ -z $CDDADIR ]
#then
#CDDADIR="/home/$USER/Cataclysm-DDA/"
#fi
#echo "Please input the name of your server"
#read SERVERNAME
#if [ -z $SERVERNAME ]
#then
#SERVERNAME=MYSERVERNAMEHERE
#fi
SERVERNAME="roguenexus"
# CDDASUBDIR from include/config.h; aka cataclysm subdir inside chroot
CDDASUBDIR="/games/cdda/"
# dir for shared files
DGLROOT="dgldir/"

SHARE_DIR="dgldir/share/"
CDDA_SHARED_FILES="dgldir/share/cdda/"

# only define this if dgl was configured with --enable-sqlite
SQLITE_DBFILE="dgldir/dgamelaunch.db"

# END OF CONFIG
##############################################################################

errorexit()
{
    echo "Error: $@" >&2
    exit 1
}

findlibs()
{
  for i in "$@"; do
      if [ -z "`ldd "$i" | grep 'not a dynamic executable'`" ]; then
         echo $(ldd "$i" | awk '{ print $3 }' | egrep -v ^'\(')
         echo $(ldd "$i" | grep 'ld-linux' | awk '{ print $1 }')
      fi
  done
}

##############################################################################

if [ -z "$TERMDATA" ]; then
    SEARCHTERMDATA="/etc/terminfo /usr/share/lib/terminfo /usr/share/terminfo /lib/terminfo"
    for dir in $SEARCHTERMDATA; do
	if [ -e "$dir/x/xterm" ]; then
	    TERMDATA="$TERMDATA $dir"
	fi
    done
    if [ -z "$TERMDATA" ]; then
	errorexit "Couldn't find terminfo definitions. Please specify in 'TERMDATA' variable."
    fi
fi



# remove trailing slash, if any
CHROOT="`echo ${CHROOT%/}`"

set -e
umask 022

if [ -e "$CHROOT" ]; then
   errorexit "Chroot $CHROOT already exists."
fi

CURDIR="`pwd`"

if [ ! -e "$CURDIR/dgamelaunch" ]; then
   errorexit "Cannot find dgamelaunch in $CURDIR"
fi

DGLFILE="dgamelaunch.`date +%Y%m%d`"

echo "Setting up chroot in $CHROOT"

LIBS="`findlibs dgamelaunch`"

mkdir -p "$CHROOT" || errorexit "Cannot create chroot"
cd "$CHROOT"
mkdir dgldir etc lib mail usr bin
chown "$USRGRP" dgldir mail
cp "$CURDIR/dgamelaunch" "$DGLFILE"
ln -s "$DGLFILE" dgamelaunch

mkdir -p "$CHROOT/dgldir/inprogress-cdda"
mkdir -p "$CHROOT/dgldir/userdata"
chown "$USRGRP" "$CHROOT/dgldir/inprogress-cdda"
chown "$USRGRP" "$CHROOT/dgldir/userdata"


if [ -n "$SQLITE_DBFILE" ]; then
  if [ "x`which sqlite3`" = "x" ]; then
      errorexit "No sqlite3 found."
  else
      echo "Creating SQLite database at $SQLITE_DBFILE"
      SQLITE_DBFILE="`echo ${SQLITE_DBFILE%/}`"
      SQLITE_DBFILE="`echo ${SQLITE_DBFILE#/}`"
      sqlite3 "$CHROOT/$SQLITE_DBFILE" "create table dglusers (id integer primary key, username text, email text, env text, password text, flags integer);"
      chown "$USRGRP" "$CHROOT/$SQLITE_DBFILE"
  fi
fi


if [ -n "$COMPRESSBIN" -a -e "`which $COMPRESSBIN`" ]; then
  COMPRESSDIR="`dirname $COMPRESSBIN`"
  COMPRESSDIR="`echo ${COMPRESSDIR%/}`"
  COMPRESSDIR="`echo ${COMPRESSDIR#/}`"
  echo "Copying $COMPRESSBIN to $COMPRESSDIR"
  mkdir -p "$COMPRESSDIR"
  cp "`which $COMPRESSBIN`" "$COMPRESSDIR/"
  LIBS="$LIBS `findlibs $COMPRESSBIN`"
fi


mkdir -p dev
cd dev
mknod urandom c 1 9
cd ..


cd etc

echo "Copying dgamelaunch to chroot"
cp "$CURDIR/examples/dgamelaunch.conf" .

echo "editing dgamelaunch.conf to use the correct server name"
sed -i "s/MYSERVERNAMEHERE/$SERVERNAME/g" ./dgamelaunch.conf

[ -f /etc/localtime ] && cp /etc/localtime .
cd ..

mkdir banners
cp -r "$CURDIR/examples/banners/" banners
#cp "$CURDIR/examples/dgl_menu_main_user.txt" ./banners
#cp "$CURDIR/examples/dgl_menu_watchmenu_help.txt" ./banners
#cp "$CURDIR/examples/dgl-banner" ./banners
cd banners
chmod go+r *
cd ..
chown -R "$USRGRP" "$CHROOT/banners"
#chown -R "$USRGRP" "$CHROOT/$SHARE_DIR"


mkdir -p "$CHROOT/$CDDASUBDIR"
if [ -n "$CDDABIN" -a ! -e "$CDDABIN" ]; then
  errorexit "Cannot find Cataclysm-DDA binary $CDDABIN"
fi

if [ -n "$CDDABIN" -a -e "$CDDABIN" ]; then
  echo "Copying $CDDABIN"
  cd "$CDDASUBDIR"
  echo "-pwd is `pwd`"
  CDDABINFILE="`basename $CDDABIN`.`date +%Y%m%d`"
  echo "-copying $CDDABIN to $CDDABINFILE"
  cp "$CDDABIN" "$CDDABINFILE"
  echo "-creating symlink cataclysm to $CDDABINFILE"
  ln -s "$CDDABINFILE" cataclysm
  LIBS="$LIBS `findlibs $CDDABIN`"
  cd "$CHROOT"
fi


mkdir -p "$CHROOT/$CDDA_SHARED_FILES"
DATAFILES="data/*"

if [ -n "$CDDA_SHARED_FILES" -a -d "$CDDA_SHARED_FILES" ]; then
  echo "Copying Cataclysm-DDA shared data"
  cp -LR $CDDADIR$DATAFILES "$CHROOT/$CDDA_SHARED_FILES"
  SHARED_DATA="data lua lang gfx"
  for fil in $SHARED_DATA; do
    cp -LR $CDDADIR$fil "$CHROOT/$CDDA_SHARED_FILES"
  done
fi

chown -R "$USRGRP" "$CHROOT/$CDDASUBDIR"
chown -R "$USRGRP" "$CHROOT/$CDDA_SHARED_FILES"
#chown -R "$USRGRP" "$CHROOT/$SHARE_DIR"

# Curses junk
if [ -n "$TERMDATA" ]; then
    echo "Copying termdata files from $TERMDATA"
    for termdat in $TERMDATA; do
	mkdir -p "$CHROOT`dirname $termdat`"
	if [ -d $termdat/. ]; then
		cp -LR $termdat/. $CHROOT$termdat
	else
		cp $termdat $CHROOT`dirname $termdat`
	fi
    done
fi


LIBS=`for lib in $LIBS; do echo $lib; done | sort | uniq`
echo "Copying libraries:" $LIBS
for lib in $LIBS; do
        mkdir -p "$CHROOT`dirname $lib`"
        cp $lib "$CHROOT/$lib"
done

echo "Copying locale"
mkdir -p $CHROOT/usr/lib/locale/
cp -LR /usr/lib/locale/* $CHROOT/usr/lib/locale/

echo "chowning  $CHROOT/$DGLROOT to make sure the permissions are correct"
chown -R "$USERGRP" "$CHROOT/$DGLROOT"

echo "Go to $CHROOT, execute dgamelaunch as root, and create an 'admin' user before setting up ssh/telnet!"
echo "You should also use this opportunity to test if Cataclysm-DDA runs, if it doesn't please contact me at codehero@nerdpol.ch or C0DEHERO on github."

echo "Finished."


